environment:
  language: java
  language_versions: 1.6.0_24
  
build:
  info:
    - echo "Env:" ; env
    - java -version
    - git clone https://github.com/paulkling/gs-spring-boot.git
    - ls -la
  run: gs-spring-boot/gradlew build 

