environment:
  language: java
  language_versions: 1.6.0_24
  
build:
  before:
    - git clone https://github.com/paulkling/gs-spring-boot.git
    - cd gs-spring-boot
  info:
    - echo "Env:" ; env
    - java -version
    - ls -la
    - chmod 777 gs-spring-boot/gradlew
  run: gradlew build 

