environment:
  language: java
  language_versions: 1.6.0_24
  
build:
  before:
  info:
    - echo "Env:" ; env
    - java -version
    - git clone https://github.com/paulkling/gs-spring-boot.git
    - cd gs-spring-boot
    - ls -la
    - chmod 777 gradlew
    - ls -la
  run: 
    - pwd
    - cd gs-spring-boot
    - gradlew build 

